### ISSUE TITLE
TypeError: Cannot destructure property 'issues' of 'result' as it is undefined.

### ISSUE THREAD

**Issue by tylermaran** [rysolv/rysolv#225]
Getting this error on unauthenticated pages, and any failed sign-in:
```
TypeError: Cannot destructure property 'issues' of 'result' as it is undefined.
    at Object.signIn (C:\Users\tyler\Desktop\code\rysolv\server\graphql\resolvers\users\signIn.js:37:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Comes from:
https://github.com/rysolv/rysolv/blob/master/server/graphql/resolvers/users/signIn.js#L37
```
const result = await getUserSettingsQuery({ userId });
const { issues, repos } = result;
```

**Comment by tylermaran** [comment]
closed with #243
